/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectOptions } from "./components/multi-select/multi-select.interface";
export { SelectOptions } from "./components/multi-select/multi-select.interface";
export namespace Components {
    interface MultiSelect {
        /**
          * Adds multiple select functionality
         */
        "multiple": boolean;
        /**
          * List of items to displayed in the dropdown
         */
        "options": SelectOptions;
        /**
          * Selected items value
         */
        "value": any;
    }
    interface MultiSelectOption {
        "value": string;
    }
}
export interface MultiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMultiSelectElement;
}
export interface MultiSelectOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMultiSelectOptionElement;
}
declare global {
    interface HTMLMultiSelectElement extends Components.MultiSelect, HTMLStencilElement {
    }
    var HTMLMultiSelectElement: {
        prototype: HTMLMultiSelectElement;
        new (): HTMLMultiSelectElement;
    };
    interface HTMLMultiSelectOptionElement extends Components.MultiSelectOption, HTMLStencilElement {
    }
    var HTMLMultiSelectOptionElement: {
        prototype: HTMLMultiSelectOptionElement;
        new (): HTMLMultiSelectOptionElement;
    };
    interface HTMLElementTagNameMap {
        "multi-select": HTMLMultiSelectElement;
        "multi-select-option": HTMLMultiSelectOptionElement;
    }
}
declare namespace LocalJSX {
    interface MultiSelect {
        /**
          * Adds multiple select functionality
         */
        "multiple"?: boolean;
        /**
          * Handler for clicking an item
         */
        "onChange"?: (event: MultiSelectCustomEvent<any>) => void;
        /**
          * List of items to displayed in the dropdown
         */
        "options"?: SelectOptions;
        /**
          * Selected items value
         */
        "value"?: any;
    }
    interface MultiSelectOption {
        "onMultiSelectOptMouseEnter"?: (event: MultiSelectOptionCustomEvent<any>) => void;
        "onMultiSelectOptionClick"?: (event: MultiSelectOptionCustomEvent<any>) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "multi-select": MultiSelect;
        "multi-select-option": MultiSelectOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "multi-select": LocalJSX.MultiSelect & JSXBase.HTMLAttributes<HTMLMultiSelectElement>;
            "multi-select-option": LocalJSX.MultiSelectOption & JSXBase.HTMLAttributes<HTMLMultiSelectOptionElement>;
        }
    }
}
