/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SelectWeb {
        /**
          * Adds multiple select functionality
         */
        "multiple": boolean;
        /**
          * List of items to displayed in the dropdown
         */
        "options": any[];
        /**
          * Selected items value
         */
        "value": any;
    }
    interface SelectWebOption {
        "value": string;
    }
}
export interface SelectWebCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSelectWebElement;
}
export interface SelectWebOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSelectWebOptionElement;
}
declare global {
    interface HTMLSelectWebElement extends Components.SelectWeb, HTMLStencilElement {
    }
    var HTMLSelectWebElement: {
        prototype: HTMLSelectWebElement;
        new (): HTMLSelectWebElement;
    };
    interface HTMLSelectWebOptionElement extends Components.SelectWebOption, HTMLStencilElement {
    }
    var HTMLSelectWebOptionElement: {
        prototype: HTMLSelectWebOptionElement;
        new (): HTMLSelectWebOptionElement;
    };
    interface HTMLElementTagNameMap {
        "select-web": HTMLSelectWebElement;
        "select-web-option": HTMLSelectWebOptionElement;
    }
}
declare namespace LocalJSX {
    interface SelectWeb {
        /**
          * Adds multiple select functionality
         */
        "multiple"?: boolean;
        /**
          * Handler for clicking an item
         */
        "onChange"?: (event: SelectWebCustomEvent<any>) => void;
        /**
          * List of items to displayed in the dropdown
         */
        "options"?: any[];
        /**
          * Selected items value
         */
        "value"?: any;
    }
    interface SelectWebOption {
        "onMultiSelectOptMouseEnter"?: (event: SelectWebOptionCustomEvent<any>) => void;
        "onMultiSelectOptionClick"?: (event: SelectWebOptionCustomEvent<any>) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "select-web": SelectWeb;
        "select-web-option": SelectWebOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "select-web": LocalJSX.SelectWeb & JSXBase.HTMLAttributes<HTMLSelectWebElement>;
            "select-web-option": LocalJSX.SelectWebOption & JSXBase.HTMLAttributes<HTMLSelectWebOptionElement>;
        }
    }
}
